---
modules-search:
    - shell
    - calamares

sequence:
    - show:
        - welcome
        - locale
        - keyboard
        - partition
        - users
        - kickos-de
        - kickos-gaming
        - kickos-bootloader
        - summary
    - exec:
        - kickos-install
        - install
    - show:
        - finished
